### ISSUE TITLE
translate with deeple

### ISSUE THREAD

**Issue by Henry2o1o** [Furniel/AiLocalizerUpdates#1]
with Deepl, is that possible?

https://www.deepl.com/translator

**Comment by Furniel** [comment]
Yes and no. On the one hand it's not hard to add one more translator to aiLocalizer( DeepL has good API), but on other hand looks like deepl isn't free even for  1 mil characters per month. There is no info about prices on their site, so i filled up sales form to check if api is really paid. I'll post their response here, but if it's not free it won't be possible integrate it to aiLocalizer(it's free tool and i can't use paid translation services in it).

**Comment by Henry2o1o** [comment]
Thank you for the fast answer. I understand.

**Comment by Furniel** [comment]
Ok, added Deepl to AiLocalizer 2.9.0.0. I didn't used official api, so it works at this moment, but may be blocked in future.
